Resolve shellcheck error in test workflow
```
ShellCheck - shell script analysis tool
version: 0.9.0
license: GNU General Public License, version 3
website: https://www.shellcheck.net

In ./bin/functions line 179:
    if [ $? -ne 0 ]; then
         ^-- SC2181 (style): Check exit code directly with e.g. 'if ! mycmd;', not indirectly with $?.

For more information:
  https://www.shellcheck.net/wiki/SC2181 -- Check exit code directly with e.g...
##[error]Process completed with exit code 1.
```

diff --git a/bin/functions b/bin/functions
--- a/bin/functions
+++ b/bin/functions
@@ -165,21 +165,17 @@ function install {
     ${SHA256SUM} -c <<<"${checksum}  ${package_filename}"
 
     case "${package_filename}" in
-        *zip) unzip "${package_filename}"
-              ;;
-        *tar.gz) tar xf "${package_filename}"
-                 ;;
-        *tgz) tar xf "${package_filename}"
-                 ;;
-        *) echo "Cannot extract ${package_filename}"
-           exit 1
-           ;;
-    esac
-
-    if [ $? -ne 0 ]; then
-        echo "Failed to extract ${package_filename}"
+    *zip)
+        unzip "${package_filename}" || { echo "Failed to extract ${package_filename}" >&2; exit 1; }
+        ;;
+    *tar.gz|*tgz)
+        tar xf "${package_filename}" || { echo "Failed to extract ${package_filename}" >&2; exit 1; }
+        ;;
+    *)
+        echo "Cannot extract ${package_filename}: unsupported file type." >&2
         exit 1
-    fi
+        ;;
+    esac
 
     read -r -a dirs <<<"$(ls -d ./*/)"
     cd "${dirs[0]}" || return 1
